### ISSUE TITLE
@conda-forge-admin, please add user @yuzie007

### ISSUE THREAD

**Issue by yuzie007** [conda-forge/elpa-feedstock#19]
### Additional comment:

First of all, thank you very much @awvwgk for your development and maintenance of many packages for quantum chemistry and computational materials science!

Here I would like to address the issue in #16, and for that I wish to request the maintainer's role, if you do not mind. Although I am not super familiar with conda-forge systems, it seems in that PR there is a merge conflict, and to solve this, we probably need some interaction with @regro-cf-autotick-bot. If I understand correctly, for that we need the maintainer's role.

If you are hesitant to have other maintainers (this is fully understandable for me), could you maybe try e.g. to add label `bot-rerun` in the PR #16? While I am not 100% sure what will happen, this hopefully give us some more hints to solve the merge conflict.

**Comment by awvwgk** [comment]
Thanks for volunteering to help with the OSX/Arm64 migration. If you want to help with the build feel free to do so, you don't need to interact with the generated PR for this nor do you need maintainer access to the feedstock. Please open a PR based on the main branch adding the migration and rerender the feedstock. Once the build passes I am happy to merge it.

**Comment by yuzie007** [comment]
Thank you @awvwgk for your feedback!

I thank you also for your suggestions about new PRs. I however would like to use the auto-migrator of @regro-cf-autotick-bot as far as possible. It is probably dangerous to implement something by ourselves by hand from scratch for this type of migrations.

As far as I understand, the problem in #16 is that, the forked repository of @regro-cf-autotick-bot is not sync-ed with the present latest original repository. This resulted in the merge conflict. (Also, the present original master is not updated with conda smithy. cf. #21, and therefore auto tests in new PRs (e.g. #20) do not succeed anyway). Without updating the fork of @regro-cf-autotick-bot in some way, we unfortunately cannot utilize its auto-migrator.

I believe, what we can do here are (regardless if we continue with #16 or open a new PR):
- Sync the forked repo in @regro-cf-autotick-bot (as far as I read [the official document](https://conda-forge.org/docs/maintainer/updating_pkgs.html#pushing-to-regro-cf-autotick-bot-branch), maintainers can do that)
- Very likely we should re-render the feed-stock with conda-smithy to update it
- Rerun auto-migrator of @regro-cf-autotick-bot (I hope we can do this with the `bot-rerun` label in that PR. I cannot do that because I have no maintainer role)

If you would like other volunteers to work on PRs *without* relying on the bots, I can still work on locally by hand with my forked repo, but as written above, I believe there is an easier and more reasonable way.

May I ask you a comment on the above?
